import 'lang_service.dart';

class Strings {
  static final Map<String, Map<String, String>> _dict = {
    'fr': {
      'enter': 'Entrer',
      'choose_language': 'Choisissez votre langue',
      'menu': 'Menu',
      'history': 'Historique',
      'services': 'Services',
      'cart': 'Panier',
      'total': 'Total',
      'your_cart': 'Votre panier',
      'table': 'Table',
      'notes': 'Notes (sans oignons, etc.)',
      'request_bill': 'Facture',
      'previous_order': 'Commande précédente',
      'details': 'Détails',
      'no_previous_order': 'Aucune commande précédente',
      'validate_order': 'Valider la commande',
      'fill_table': 'Indiquez la table',
      'empty_cart': 'Panier vide',
      'added_to_cart': 'Ajouté au panier',
      'error': 'Erreur',
      'bill': 'Facture',
      'paid': 'Déjà payé:',
      'remaining': 'Restant:',
      'tip': 'Pourboire',
      'to_pay': 'À régler',
      'pay_selection': 'Payer la sélection',
      'language': 'Langue',
      'glasses_type': 'Type de verre',
      'quantity': 'Quantité',
      'cancel': 'Annuler',
      'send': 'Envoyer',
      'drinks': 'Boissons',
      'spirits': 'Spiritueux',
      'dishes': 'Plats',
      'call': 'Appeler',
      'cancel': 'Annuler',
      'send': 'Envoyer',
      'service_clear': 'Débarrasser',
      'service_cutlery': 'Demander un couvert',
      'service_glasses': 'Demander des verres',
      'service_ice': 'Demander des glaçons',
      'service_cleaning': 'Nettoyage (casse)',
      'loading': 'Chargement...',
    },
    'en': {
      'enter': 'Enter',
      'choose_language': 'Choose your language',
      'menu': 'Menu',
      'history': 'History',
      'services': 'Services',
      'cart': 'Cart',
      'total': 'Total',
      'your_cart': 'Your cart',
      'table': 'Table',
      'notes': 'Notes (no onions, etc.)',
      'request_bill': 'Bill',
      'previous_order': 'Previous order',
      'details': 'Details',
      'no_previous_order': 'No previous order',
      'validate_order': 'Place order',
      'fill_table': 'Enter the table',
      'empty_cart': 'Empty cart',
      'added_to_cart': 'Added to cart',
      'error': 'Error',
      'bill': 'Bill',
      'paid': 'Paid:',
      'remaining': 'Remaining:',
      'tip': 'Tip',
      'to_pay': 'To pay',
      'pay_selection': 'Pay selection',
      'language': 'Language',
      'glasses_type': 'Glass type',
      'quantity': 'Quantity',
      'cancel': 'Cancel',
      'send': 'Send',
      'drinks': 'Drinks',
      'spirits': 'Spirits',
      'dishes': 'Dishes',
      'call': 'Call',
      'cancel': 'Cancel',
      'send': 'Send',
      'service_clear': 'Clear table',
      'service_cutlery': 'Request cutlery',
      'service_glasses': 'Request glasses',
      'service_ice': 'Request ice',
      'service_cleaning': 'Cleaning (breakage)',
      'loading': 'Loading...',
    },
    'ar': {
      'enter': 'دخول',
      'choose_language': 'اختر لغتك',
      'menu': 'القائمة',
      'history': 'السجل',
      'services': 'الخدمات',
      'cart': 'السلة',
      'total': 'الإجمالي',
      'your_cart': 'سلتك',
      'table': 'الطاولة',
      'notes': 'ملاحظات (بدون بصل...)',
      'request_bill': 'فاتورة',
      'previous_order': 'الطلب السابق',
      'details': 'تفاصيل',
      'no_previous_order': 'لا توجد طلبات سابقة',
      'validate_order': 'تأكيد الطلب',
      'fill_table': 'أدخل رقم الطاولة',
      'empty_cart': 'السلة فارغة',
      'added_to_cart': 'تمت الإضافة للسلة',
      'error': 'خطأ',
      'bill': 'فاتورة',
      'paid': 'مدفوع:',
      'remaining': 'المتبقي:',
      'tip': 'بقشيش',
      'to_pay': 'المبلغ المستحق',
      'pay_selection': 'دفع العناصر المحددة',
      'language': 'اللغة',
      'glasses_type': 'نوع الكأس',
      'quantity': 'الكمية',
      'cancel': 'إلغاء',
      'send': 'إرسال',
      'drinks': 'مشروبات',
      'spirits': 'كحوليات',
      'dishes': 'أطباق',
      'call': 'نداء',
      'cancel': 'إلغاء',
      'send': 'إرسال',
      'service_clear': 'تنظيف الطاولة',
      'service_cutlery': 'طلب أدوات مائدة',
      'service_glasses': 'طلب كؤوس',
      'service_ice': 'طلب ثلج',
      'service_cleaning': 'تنظيف (كسر)',
      'loading': 'جارٍ التحميل...',
    },
    'de': {
      'enter': 'Eintreten',
      'choose_language': 'Sprache wählen',
      'menu': 'Menü',
      'history': 'Verlauf',
      'services': 'Service',
      'cart': 'Warenkorb',
      'total': 'Summe',
      'your_cart': 'Ihr Warenkorb',
      'table': 'Tisch',
      'notes': 'Notizen (ohne Zwiebeln usw.)',
      'request_bill': 'Rechnung',
      'previous_order': 'Vorherige Bestellung',
      'details': 'Details',
      'no_previous_order': 'Keine vorherige Bestellung',
      'validate_order': 'Bestellung bestätigen',
      'fill_table': 'Tisch angeben',
      'empty_cart': 'Warenkorb leer',
      'added_to_cart': 'Zum Warenkorb hinzugefügt',
      'error': 'Fehler',
      'bill': 'Rechnung',
      'paid': 'Bezahlt:',
      'remaining': 'Rest:',
      'tip': 'Trinkgeld',
      'to_pay': 'Zu zahlen',
      'pay_selection': 'Auswahl bezahlen',
      'language': 'Sprache',
      'glasses_type': 'Glasart',
      'quantity': 'Menge',
      'cancel': 'Abbrechen',
      'send': 'Senden',
      'drinks': 'Getränke',
      'spirits': 'Spirituosen',
      'dishes': 'Speisen',
      'call': 'Rufen',
      'cancel': 'Abbrechen',
      'send': 'Senden',
      'service_clear': 'Abräumen',
      'service_cutlery': 'Besteck anfordern',
      'service_glasses': 'Gläser anfordern',
      'service_ice': 'Eis anfordern',
      'service_cleaning': 'Reinigung (Bruch)',
      'loading': 'Laden...',
    },
    'it': {
      'enter': 'Entra',
      'choose_language': 'Scegli lingua',
      'menu': 'Menu',
      'history': 'Cronologia',
      'services': 'Servizi',
      'cart': 'Carrello',
      'total': 'Totale',
      'your_cart': 'Il tuo carrello',
      'table': 'Tavolo',
      'notes': 'Note (senza cipolle ecc.)',
      'request_bill': 'Conto',
      'previous_order': 'Ordine precedente',
      'details': 'Dettagli',
      'no_previous_order': 'Nessun ordine precedente',
      'validate_order': 'Conferma ordine',
      'fill_table': 'Indica il tavolo',
      'empty_cart': 'Carrello vuoto',
      'added_to_cart': 'Aggiunto al carrello',
      'error': 'Errore',
      'bill': 'Conto',
      'paid': 'Pagato:',
      'remaining': 'Rimanente:',
      'tip': 'Mancia',
      'to_pay': 'Da pagare',
      'pay_selection': 'Paga selezione',
      'language': 'Lingua',
      'glasses_type': 'Tipo bicchiere',
      'quantity': 'Quantità',
      'cancel': 'Annulla',
      'send': 'Invia',
      'drinks': 'Bevande',
      'spirits': 'Alcolici',
      'dishes': 'Piatti',
      'call': 'Chiama',
      'cancel': 'Annulla',
      'send': 'Invia',
      'service_clear': 'Sgombera',
      'service_cutlery': 'Richiedi posate',
      'service_glasses': 'Richiedi bicchieri',
      'service_ice': 'Richiedi ghiaccio',
      'service_cleaning': 'Pulizia (rottura)',
      'loading': 'Caricamento...',
    },
  };

  static String t(String key) {
    final lang = LangService.instance.lang;
    return _dict[lang]?[key] ?? _dict['fr']?[key] ?? key;
  }
}


